github_keys_create_install_user: false
github_keys_install_user: deploy
github_keys_github_users:
  - oestrich

nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "443"
    server_name: "blog.oestrich.org"
    root: "/home/deploy/sites/blog.oestrich.org/"
    index: "index.html"
    filename: "blog.oestrich.org.conf"
    extra_parameters: |
      ssl    on;
      ssl_certificate    /home/deploy/ssl/blog_oestrich_org.crt;
      ssl_certificate_key    /home/deploy/ssl/blog_oestrich_org.key;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
      ssl_session_cache shared:SSL:10m;

      gzip on;
      gzip_proxied any;
      gzip_types text/plain text/xml text/css application/x-javascript;
      gzip_vary on;
      gzip_disable “msie6″;

      location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 1h;
        add_header Pragma public;
        add_header Cache-Control "public";
      }
  - listen: "80"
    server_name: "blog.oestrich.org"
    root: "/home/deploy/sites/blog.oestrich.org/"
    index: "index.html"
    filename: "blog.oestrich.org.80.conf"
    extra_parameters: |
      gzip on;
      gzip_proxied any;
      gzip_types text/plain text/xml text/css application/x-javascript;
      gzip_vary on;
      gzip_disable “msie6″;

      location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 1h;
        add_header Pragma public;
        add_header Cache-Control "public";
      }
  - listen: "80"
    server_name: "oestrich.org"
    root: "/home/deploy/sites/oestrich.org/"
    index: "index.html"
    filename: "oestrich.org.conf"
  - listen: "80"
    server_name: "exventure.org"
    root: "/home/deploy/sites/exventure.org/"
    index: "index.html"
    filename: "exventure.org.conf"

sites:
  - name: blog.oestrich.org
    repo: https://github.com/oestrich/blog.oestrich.org.git
    command: |
      bundle install --deployment
      bundle exec jekyll build -s $TMP_GIT_CLONE -d $PUBLIC_WWW
  - name: oestrich.org
    repo: https://github.com/oestrich/oestrich.org.git
    command: |
      rsync -r . $PUBLIC_WWW
  - name: exventure.org
    repo: https://github.com/oestrich/ex_venture.git
    command: |
      export LC_ALL=C.UTF-8
      export LANG=C.UTF-8
      mkdocs build -d $PUBLIC_WWW

ssh_permit_tunnel: true
ssh_allow_tcp_forwarding: true
ssh_allow_agent_forwarding: true
ssh_print_motd: true
ssh_print_last_log: true
